In [2]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import os

In [3]:
# loop through data, see if they are nan and inf

movement_dir = 'data/moving/'

In [18]:
bad_recs = []
for f in os.listdir(movement_dir):
    sample = np.load(movement_dir + f)

    if np.isnan(sample.sum()):
        if f.split('_')[:2] not in bad_recs:
            bad_recs.append(f.split('_')[:2])
        #print("Noah you messed up")
        print(f)
        #break

180328_001_0_win331_move.npy
180328_001_0_win519_move.npy
180328_001_0_win525_move.npy
180328_001_0_win344_move.npy
180328_001_0_win383_move.npy
180328_001_0_win621_move.npy
180328_001_0_win55_move.npy
180328_001_0_win39_move.npy
180328_001_0_win345_move.npy
180328_001_0_win491_move.npy
180328_001_0_win272_move.npy
180328_001_0_win183_move.npy
180328_001_0_win346_move.npy
180328_001_0_win548_move.npy
180328_001_0_win570_move.npy
180328_001_0_win266_move.npy
180328_001_0_win152_move.npy
180328_001_0_win472_move.npy
180328_001_0_win217_move.npy
180328_001_0_win32_move.npy
180328_001_0_win271_move.npy
180328_001_0_win274_move.npy
180328_001_0_win30_move.npy
180328_001_0_win279_move.npy
180328_001_0_win424_move.npy
180328_001_0_win191_move.npy
180328_001_0_win225_move.npy
180328_001_0_win21_move.npy
180328_001_0_win10_move.npy
180328_001_0_win592_move.npy
180328_001_0_win311_move.npy
180328_001_0_win299_move.npy
180328_001_0_win606_move.npy
180328_001_0_win109_move.npy
180328_001_0_win148_

180328_001_0_win284_move.npy
180328_001_0_win219_move.npy
180328_001_0_win263_move.npy
180328_001_0_win134_move.npy
180328_001_0_win234_move.npy
180329_003_0_win13_move.npy
180328_001_0_win569_move.npy
180328_001_0_win145_move.npy
180328_001_0_win443_move.npy
180328_001_0_win96_move.npy
180328_001_0_win581_move.npy
180328_001_0_win34_move.npy
180328_001_0_win252_move.npy
180328_001_0_win567_move.npy
180328_001_0_win277_move.npy
180328_001_0_win214_move.npy
180328_001_0_win203_move.npy
180328_001_0_win38_move.npy
180328_001_0_win240_move.npy
180328_001_0_win363_move.npy
180328_001_0_win248_move.npy
180328_001_0_win523_move.npy
180328_001_0_win541_move.npy
180328_001_0_win45_move.npy
180328_001_0_win27_move.npy
180328_001_0_win482_move.npy
180328_001_0_win421_move.npy
180328_001_0_win26_move.npy
180328_001_0_win91_move.npy
180328_001_0_win257_move.npy
180328_001_0_win238_move.npy
180328_001_0_win14_move.npy
180328_001_0_win477_move.npy
180328_001_0_win501_move.npy
180328_001_0_win192_mov

180328_001_0_win42_move.npy
180328_001_0_win293_move.npy
180328_001_0_win99_move.npy
180328_001_0_win526_move.npy
180328_001_0_win418_move.npy
180328_001_0_win108_move.npy
180328_001_0_win314_move.npy
180328_001_0_win537_move.npy
180328_001_0_win33_move.npy
180328_001_0_win467_move.npy
180328_001_0_win308_move.npy
180328_001_0_win75_move.npy
180328_001_0_win171_move.npy
180328_001_0_win321_move.npy
180328_001_0_win613_move.npy
180328_001_0_win153_move.npy
180328_001_0_win247_move.npy
180328_001_0_win215_move.npy
180328_001_0_win36_move.npy
180328_001_0_win599_move.npy
180328_001_0_win5_move.npy
180328_001_0_win360_move.npy
180328_001_0_win351_move.npy
180328_001_0_win426_move.npy
180328_001_0_win59_move.npy
180328_001_0_win155_move.npy
180328_001_0_win521_move.npy
180328_001_0_win181_move.npy
180328_001_0_win530_move.npy
180328_001_0_win633_move.npy
180328_001_0_win288_move.npy
180328_001_0_win44_move.npy
180328_001_0_win269_move.npy
180328_001_0_win494_move.npy
180328_001_0_win397_mov

In [19]:
bad_recs

[['180328', '001'],
 ['180330', '007'],
 ['180327', '004'],
 ['180327', '002'],
 ['180330', '004'],
 ['180328', '005'],
 ['180327', '005'],
 ['180329', '003']]

In [20]:
from scipy.io import loadmat

In [28]:
# start with 180327   006
for badrec in bad_recs:
    night = badrec[0]
    rec = badrec[1]
    allspec = loadmat('../Spectrogram_mat_data/N10W1dn1_'+ night + '_rec'+rec+'.mat')
   # night_events = loadmat('/vol/sas2b/Goose_Multiscale_M1_Wireless/'+night+'/'+rec+'/rec'+rec+'.NightEvents.mat')
   # video_start = night_events['NightEvents'][0][0][0][0][0][0][0][0]
   # video_stop = night_events['NightEvents'][0][0][0][0][0][1][0][0]
   # video_length = video_stop - video_start
   # break
    print(night,rec)
    ch=1
    spec = allspec['Spec_per_Ch'][0][0][ch][0][0][0]  
    print(spec)
    print()

180328 001
[[0.75940934 0.74408132 0.73632667 ... 0.53424233 0.52041644 0.47682514]
 [0.77417067 0.75635533 0.76184084 ... 0.53553827 0.5268238  0.48947616]
 [0.77558    0.75831544 0.76352138 ... 0.53636507 0.53136453 0.49273322]
 ...
 [0.20346051 0.19970973 0.21607617 ... 0.22211343 0.20250447 0.21629441]
 [0.1955292  0.19285171 0.21014395 ... 0.22189151 0.20453368 0.20868566]
 [0.19344511 0.19352835 0.20807774 ... 0.22001912 0.20475641 0.20279858]]

180330 007
[[ 0.84922732  0.72311844  0.70337874 ... -0.71713239 -0.23344582
   0.01755205]
 [ 1.15466201  1.09425353  1.06634689 ... -0.59037391 -0.17391741
  -0.02098651]
 [ 1.07419314  1.01748315  1.01444002 ... -0.4868414   0.01597296
  -0.28320554]
 ...
 [-0.7187759  -0.75270401 -0.73616801 ... -0.37684482 -0.26650524
  -0.35940389]
 [-0.91783277 -0.75570921 -0.65915132 ... -0.06103666  0.06677526
  -0.28072393]
 [-1.21029908 -1.10961575 -1.06342261 ...  0.17690814  0.45343586
  -0.23307696]]

180327 004
[[ 0.35427401  0.31795709  0.

In [22]:
night

'180328'

In [23]:
rec

'001'

In [24]:
allspec

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Mon Nov  2 02:52:18 2020',
 '__version__': '1.0',
 '__globals__': [],
 'Spec_per_Ch': array([[(array([[(array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]), array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]), array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        ...,
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan